<h1 style="color:SkyBlue">Python Basics</h1>

* Python is general-purpose, high-level programming language. <br>
* It supports both function and Object Oriented Programming.

In [3]:
#python Hello world
print("Hello, World!")

Hello, World!

<h1 style="color:SkyBlue">Python Indentation</h1>
<b>Indentation refers to the spaces at the beginning of a code line.

In [7]:
if 29 > 11:
    print("Twenty-nine is greater than eleven!")

Five is greater than two!

In [ ]:
if 29 > 11:
    print("Twenty-nine is greater than eleven!")

In [ ]:
if 29 > 11:
    if 11 > 2:
        print("Twenty-nine is the gretest!")

<h1 style="color:SkyBlue">Python Comments</h1>

<b>Comments in python can be doe by : #, '''  '''.</b>

Comments can be used to prevent execution when testing code.

In [8]:
# print("Hello World!") 
# print("Hello World!")

<b>Comments can be used to explain Python code

In [17]:
print("Hello World!") #this is a code to print hello world

Hello World!

In [9]:
print("Hello World!")   #this is a code to print hello world

Hello World!

<h3>Multiline Comments</h3>

In [21]:
# This is a comment for hello world
# written in
# more than just one line
print("Hello World!")

Hello World!

In [22]:
'''This is a comment for hello world
written in
more than just one line'''
print("Hello World!")

Hello World!

<h1 style="color:SkyBlue">Python Variables</h1>
<b>variables are created when you assign a value to it

<h2>Variable Names</h2>

* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Variable names are case-sensitive (age, Age and AGE are three different variables)
* A variable name cannot be any of the Python keywords.

<b><h4>legal variable names:</h4><br> </b>
myvar = "Data science" <br>
my_var = "Data science" <br>
_my_var = "Data science" <br>
myVar = "Data science" <br>
MYVAR = "Data science" <br>
myvar2 = "Data science"

<b><h4>Illegal variable names:<h4></b> <br>
2myvar = "Data science" <br>
my-var = "Data science" <br>
my var = "Data science" <br>

<h4 >Camel Case</h4>
Each word, except the first, starts with a capital letter:

In [40]:
myVariableName = "Code For Change"

In [14]:
dataScience = 1

<h4 style="color:SkyBlue">Pascal Case</h4>
<b>Each word starts with a capital letter:

In [41]:
MyVariableName = "Code For Change"

<h4 style="color:SkyBlue">Snake Case</h4>
<b>Each word is separated by an underscore character:

In [43]:
my_variable_name = "Code For Change"

In [23]:
x = 5
y = "John"
print(x)
print(y)

5
John

<b>Variables do not need to be declared with any particular type, and can even change type after they have been set.

In [26]:
x = 4       # x is of type int
y = "Sally" # y is now of type str
print(x)
print(y)

4
Sally

In [2]:
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0
print(x,y,z)
print(type(x), type(y), type(z))

3 3 3.0
<class 'str'> <class 'int'> <class 'float'>

<b>You can get the data type of a variable with the <u>type()</u> function.

In [3]:
x = 4       # x is of type int
y = 8.3333333  # y is a float
z = "Sally" # x is now of type str

print(type(x), type(y), type(z))

<class 'int'> <class 'float'> <class 'str'>

<b>String variables can be declared either by using <u>single</u> or <u>double quotes</u>:

In [33]:
x = "John"
# is the same as
y = 'John'

print(x)
print(y)

John
John

<b>Variable names are <u>case-sensitive</u>.

In [21]:
a = 4
a = "Sally"
# A will not overwrite a

print(a)
print(A)

4

<h4 style="color:SkyBlue">Many Values to Multiple Variables</h4>

<b>Python allows you to assign values to multiple variables in one line

In [ ]:
x, y, z = "Orange", "Banana", "Cherry"
print(x,y,z)

Orange Banana Cherry

In [22]:
x= "Orange"
y= "Banana"
z="Cherry"

<b>And you can assign the same value to multiple variables in one line

In [46]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange

<h4 style="color:SkyBlue">Unpack a Collection</h4>

In [5]:
fruits = [1, "banana", "cherry"]
x, y, z = fruits

print(x,y,z)
type(x)

1 banana cherry

int

<h4 style="color:SkyBlue">Output Variables</h4>
<b>print() function is often used to output variables

In [51]:
x = "Python"
y = "is"
z = "awesome"
print(x, y, z)

Python is awesome

In [28]:
x = "Python "
y = "is "
z = "awesome"
print(x+y+z) # + is an operator

Python is awesome

In [31]:
x,y = 5,10
# y = 10
print(x - y)  # + is an operator,  5 and 10 are int data type

-5

In [32]:
x = 5
y = "John"
print(x + y)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [58]:
x = 5
y = "John"
print(x, y)

5 John

In [ ]:
#Exercise

<h1 style="color:SkyBlue">Python Data Types</h1>

<h2>Built-in Data Types</h2>

<b>Variables can store data of different types, and different types can do different things. <br>


* Text Type:	str
* Numeric Types:	int, float, complex
* Sequence Types:	list, tuple, range
* Mapping Type:	dict
* Set Types:	set, frozenset
* Boolean Type:	bool
* Binary Types:	bytes, bytearray, memoryview
* None Type:	NoneType

In [61]:
x = "Hello World"
print(type(x))

<class 'str'>

In [62]:
x = 20
print(type(x))

<class 'int'>

In [63]:
x = 20.5
print(type(x))

<class 'float'>

In [64]:
x = 1j
print(type(x))

<class 'complex'>

In [36]:
x = ["apple", "banana", "cherry"]
print(type(x))
x[2]

<class 'list'>

'cherry'

In [66]:
x = ("apple", "banana", "cherry")
print(type(x))

<class 'tuple'>

In [33]:
x = range(6)
print(x)
print(type(x))

range(0, 6)
<class 'range'>

In [68]:
x = {"name" : "John", "age" : 36}
print(type(x))

<class 'dict'>

In [69]:
x = {"apple", "banana", "cherry"}
print(type(x))

<class 'set'>

In [70]:
x = frozenset({"apple", "banana", "cherry"})
print(type(x))

<class 'frozenset'>

In [71]:
x = True
print(type(x))

<class 'bool'>

In [72]:
x = b"Hello"
print(type(x))

<class 'bytes'>

In [73]:
x = bytearray(5)
print(type(x))

<class 'bytearray'>

In [74]:
x = memoryview(bytes(5))
print(type(x))

<class 'memoryview'>

In [75]:
x = None
print(type(x))

<class 'NoneType'>

<h2>Python Numbers</h2>

<b>There are three numeric types in Python:

* int
* float
* complex

In [76]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>

<h3 style="color:SkyBlue">Int</h3>
<b>Int, or integer, is a whole number, positive or negative, without decimals, of unlimited length.

In [77]:
x = 1
y = 35656222554887711
z = -3255522

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'int'>

<h3 style="color:SkyBlue">Float</h3>
Float, or "floating point number" is a number, positive or negative, containing one or more decimals.

In [82]:

x = 1.10
y = 1.0
z = -35.59

a = 35e3
b = 12E4
c = -87.7e100

print(type(x))
print(type(y))
print(type(z))
print(type(a))
print(type(b))
print(type(c))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

<h3 style="color:SkyBlue">Complex</h3>
<b>Complex numbers are written with a "j" as the imaginary part:

In [83]:
x = 3+5j
y = 5j
z = -5j

print(type(x))
print(type(y))
print(type(z))

<class 'complex'>
<class 'complex'>
<class 'complex'>

<h3 style="color:SkyBlue">Type Conversion</h3>
<b>You can convert from one type to another with the int(), float(), and complex() methods

In [84]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

#convert from int to float:
a = float(x)

#convert from float to int:
b = int(y)

#convert from int to complex:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))

1.0
2
(1+0j)
<class 'float'>
<class 'int'>
<class 'complex'>

<h3>Specify a Variable Type</h3>
<b>There may be times when you want to specify a type on to a variable.

In [164]:
x = int(1)   # x will be 1
y = int(2.8) # y will be 2
z = int("3") # z will be 3

In [100]:
x = float(1)     # x will be 1.0
y = float(2.8)   # y will be 2.8
z = float("3")   # z will be 3.0
w = float("4.2") # w will be 4.2

<h2 >Strings</h2>
<b>Strings in python are surrounded by either single quotation marks, or double quotation marks.

In [102]:
print("Data science")
print('Data science')

Data science
Data science

<b>Assigning a string to a variable is done with the variable name followed by an equal sign and the string

In [104]:
a = "Data science"
print(a)

Data science

<b>You can assign a multiline string to a variable by using three quotes

In [105]:
a = """This is a bsic python class.
We start with data types, function and classes.
After basic skills in python we learn machine learning"""
print(a)

This is a bsic python class.
We start with data types, function and classes.
After basic skills in python we learn machine learning

In [106]:
a = '''This is a bsic python class.
We start with data types, function and classes.
After basic skills in python we learn machine learning'''
print(a)

This is a bsic python class.
We start with data types, function and classes.
After basic skills in python we learn machine learning

<b>Like many other popular programming languages, strings in Python are <u>arrays</u> of bytes representing unicode characters.<br>

<b>However, Python does not have a character data type, a single character is simply a string with a length of 1. <br>

<b><u>Square brackets</u> can be used to access elements of the string.

In [6]:
data_s = "Data science"
print(data_s[9])

n

<b>Since strings are arrays, we can loop through the characters in a string, with a <u>for</u> loop.

In [8]:
for x in "Data":
  print(x)
  break

D

<b>To get the length of a string, use the <u>len()</u> function.

In [115]:
a = "Data science"
print(len(a))

12

In [ ]:
# len()

<b>To check if a certain phrase or character is present in a string, we can use the keyword <u>in</u>.

In [11]:
txt = "I ate a banana"
print("eat" in txt)

False

<b>Use it in an <u>if</u> statement

In [15]:
txt = "I ate a banana"
if "banana" in txt:
  print("Yes, 'banana' is present.")
else:
    print("it is other fruit")

Yes, 'banana' is present.

<b>To check if a certain phrase or character is NOT present in a string, we can use the keyword <u>not in</u>.

In [121]:
txt = "I ate a banana"
print("expensive" not in txt)

True

In [122]:
txt = "I ate a banana"
if "expensive" not in txt:
  print("No, 'expensive' is NOT present.")

No, 'expensive' is NOT present.

<h3 style="color:SkyBlue">Slicing Strings</h3>
<b>You can return a range of characters by using the slice syntax.

In [25]:
b = "Data science"
print(b[2:])

ta science

In [26]:
b = "Data science"
print(b[:-2])

Data scien

Upper Case <br>
<b>The <u>upper()</u> method returns the string in upper case:

In [27]:
a = "science"
print(a.upper())

SCIENCE

In [29]:
"data".upper()

'DATA'

<b>Lower Case <br>
The <u>lower()</u> method returns the string in lower case:

In [133]:
a = "Data science"
print(a.lower())

data science

<b>Remove Whitespace <br>
Whitespace is the space before and/or after the actual text, and very often you want to remove this space.

<b> The <u>strip()</u> method removes any whitespace from the beginning or the end

In [32]:
a = "  Data science "
print(a)
print(a.strip()) # returns "Hello, World!"

  Data science
Data science

<b>Replace String <br>
The <u>replace()</u> method replaces a string with another string:

In [33]:
a = "Data Science"
print(a.replace("D", "Q"))

Qata Science

<b>Split String <br>
The <u>split()</u> method returns a list where the text between the specified separator becomes the list items.

In [35]:
a = "Data, science"
print(a.split("D")) # returns ['Data', ' science!']

['', 'ata, science']

<b>String Concatenation <br>
To concatenate, <u>or</u> combine, two strings you can use the <u>+</u> operator.

In [39]:
a = "Data"
b = "Science"
c = a + b
print(c)

DataScience

In [37]:
a = "Data"
b = "Science"
c = a + " " + b
print(c)

Data Science

<b>String Format <br>
we can combine strings and numbers by using the <u>format()</u> method!

In [40]:

name = 'Ram'
age = 30
place = 'Lalitpur'

txt = "My name is {name}, and I am {age} years old. I live in {place}"
z= txt.format(name=name, age=age, place=place)
z

'My name is Ram, and I am 30 years old. I live in Lalitpur'

<h3 style="color:SkyBlue;">Python Booleans</h3>
<b>Booleans represent one of two values: <u>True</u> or <u>False</u>.

In [41]:
print(10 > 9)
print(10 == 10)
print(10 < 9)

True
True
False

In [46]:
x=8
y=3
x//y

2

In [63]:
3==3

True

<h3 style="color:SkyBlue;">Python Arithmetic Operators</h3>

 <table>
  <tr>
    <th>Operator</th>
    <th>Name</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>+</td>
    <td>Addition</td>
    <td>x + y</td>
  </tr>
  <tr>
    <td>-</td>
    <td>Subtraction</td>
    <td>x - y</td>
  </tr>
      <tr>
    <td>*</td>
    <td>Multiplication</td>
    <td>x * y</td>
  </tr>
       <tr>
    <td>/</td>
    <td>Division</td>
    <td>x / y</td>
  </tr>
       <tr>
    <td>%</td>
    <td>Modulus</td>
    <td>x % y</td>
  </tr>
       <tr>
    <td>**</td>
    <td>Exponentiation</td>
    <td>x ** y</td>
  </tr>
       <tr>
    <td>//</td>
    <td>Floor division	</td>
    <td>x // y	</td>
  </tr>
     
</table>

<h3 style="color:SkyBlue;"'>Python Assignment Operators </h3>
Assignment operators are used to assign values to variables

 <table>
  <tr>
    <th>Operator</th>
    <th>Example</th>
    <th>Same As</th>
  </tr>
  <tr>
    <td>=</td>
    <td>x = 5</td>
    <td>x = 5</td>
  </tr>
  <tr>
    <td>+=</td>
    <td>x += 3</td>
    <td>x=x+3</td>
  </tr>
      <tr>
    <td>-=	</td>
    <td>x -= 3	</td>
    <td>x=x-3</td>
  </tr>
       <tr>
    <td>*=</td>
    <td>x *= 3</td>
    <td> x=x*3</td>
  </tr>
       <tr>
    <td>/=	</td>
    <td>x /= 3	</td>
    <td>x =x/3</td>
  </tr>
       <tr>
    <td>%=	</td>
    <td>x %= 3	</td>
    <td>x = x % 3	</td>
  </tr>
     
</table>

<h3 style="color:SkyBlue;">Python Comparison Operators</h3>
Comparison operators are used to compare two values:

 <table>
  <tr>
    <th>Operator</th>
    <th>Name</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>==</td>
    <td>Equal</td>
    <td>x == y</td>
  </tr>
  <tr>
    <td>!=</td>
    <td>Not equal</td>
    <td>x != y</td>
  </tr>
      <tr>
    <td>></td>
    <td>Greater than</td>
    <td>x > y</td>
  </tr>
       <tr>
    <td><</td>
    <td>Less than</td>
    <td>x < y</td>
  </tr>
       <tr>
    <td>>=</td>
    <td>Greater than or equal to</td>
    <td>x >= y</td>
  </tr>
       <tr>
    <td><=</td>
    <td>Less than or equal to</td>
    <td>x <= y</td>
  </tr>
     
</table>

<h3 style="color:SkyBlue;"> Python Logical Operators</h3>
Logical operators are used to combine conditional statements

 <table>
  <tr>
    <th>Operator</th>
    <th>Description</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>and</td>
    <td>Returns True if both statements are true</td>
    <td>x < 5 and  x < 10</td>
  </tr>
  <tr>
    <td>or</td>
    <td>Returns True if one of the statements is true</td>
    <td>x < 5 or x < 4</td>
  </tr>
      <tr>
    <td>not</td>
    <td>Reverse the result, returns False if the result is true</td>
    <td>not(x < 5 and x < 10)</td>
  </tr>  
</table>

<h3 style="color:SkyBlue;">Python Identity Operators</h3>
Identity operators are used to compare the objects, not if they are equal, but if they are actually the same object, with the same memory location

 <table>
  <tr>
    <th>Operator</th>
    <th>Description</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>is</td>
    <td>Returns True if both variables are the same object</td>
    <td>x < x is y < 10</td>
  </tr>
  <tr>
    <td>is not</td>
    <td>Returns True if both variables are not the same object</td>
    <td>x < x is not y< 4</td>
  </tr>
</table>

In [64]:
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is z)

# returns True because z is the same object as x

print(x is y)

# returns False because x is not the same object as y, even if they have the same content

print(x == y)

# to demonstrate the difference betweeen "is" and "==": this comparison returns True because x is equal to y

True
False
True

In [66]:
x = ["apple", "banana"]
y = ["apple", "car"]
z = x

print(x is not z)

# returns False because z is the same object as x

print(x is not y)

# returns True because x is not the same object as y, even if they have the same content

print(x != y)

# to demonstrate the difference betweeen "is not" and "!=": this comparison returns False because x is equal to y

False
True
True

<b><h2>Python If ... Else</h2> <br>
 
   Python supports the usual logical conditions from mathematics <br> 
    
 <table>
  <tr>
    <th>Operator</th>
    <th>Name</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>==</td>
    <td>Equal</td>
    <td>x == y</td>
  </tr>
  <tr>
    <td>!=</td>
    <td>Not equal</td>
    <td>x != y</td>
  </tr>
      <tr>
    <td>></td>
    <td>Greater than</td>
    <td>x > y</td>
  </tr>
       <tr>
    <td><</td>
    <td>Less than</td>
    <td>x < y</td>
  </tr>
       <tr>
    <td>>=</td>
    <td>Greater than or equal to</td>
    <td>x >= y</td>
  </tr>
       <tr>
    <td><=</td>
    <td>Less than or equal to</td>
    <td>x <= y</td>
  </tr>
     
</table>

<b>If statement

In [23]:
a = 33
b = 200
if b > a:
    print("b is greater than a")

b is greater than a

In [69]:
age = 8
if age >= 18:
    print("The person can vote")
else:
    print("the person cannot vote")

the person cannot vote

<b>Elif <br> </b>
    The elif keyword is Python's way of saying "if the previous conditions were not true, then try this condition"

In [73]:
a = 33
b = 34
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
# elif a!=b:
#     print("this is output")

b is greater than a

<b>Else</b> <br>
The else keyword catches anything which isn't caught by the preceding conditions.

In [19]:
# write elif condition for the code below
age = 20
if age >= 18:
    print("The person can vote")
else:
    print("The person cannot vote")

The person can vote

In [21]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a is greater than b

<h3>Python Loops</h3> <br>
Python has two primitive loop commands:<br>

* while loops<br>
* for loops<br>

<b>The while Loop</b><br>
With the while loop we can execute a set of statements as long as a condition is true.

In [77]:
# Print i as long as i is less than 6:
i = 1
while i <= 6:
  print(i)
  i += 1    #remember to increment i, or else the loop will continue forever. 
#i=i+1

1
2
3
4
5
6

<b>The break Statement</b><br>
With the break statement we can stop the loop even if the while condition is true

In [32]:
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3

<b>The continue Statement</b><br>
With the continue statement we can stop the current iteration, and continue with the next

In [35]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5
6

In [36]:
i = 1
while i < 6:
  print(i)
  i += 1
else:
  print("i is no longer less than 6")

1
2
3
4
5
i is no longer less than 6

<h3>Python For Loops</h3><br>
A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string)

In [81]:
fruits = ["apple", "banana", "cherry", 1]
for x in fruits:
  print(x)
  if x=='banana':
        break

apple
banana

In [39]:
for x in "banana":
  print(x)

b
a
n
a
n
a

In [40]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
  if x == "banana":
    break

apple
banana

In [41]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)

apple
cherry

In [52]:
for x in range(3, 6):
  print(x)

3
4
5

In [54]:
for x in range(3, 15, 4):
  print(x)

3
7
11

In [82]:
# Nested loop

In [57]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
    for y in fruits:
        print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry

In [ ]:
x= 18 #find it x and y is ood or even 
y= 3

In [66]:
x = 18

if x % 2 == 0:
    print(x,"Is Even Number")
else:
    print(x, "Is Odd Number")

y = 3

if y % 2 == 0:
    print(y,"Is Even Number")
else:
    print(y, "Is Odd Number")

18 Is Even Number
3 Is Odd Number

In [ ]:
# a = [3, 6, 99, 45]

<h2 style="color:SkyBlue;">Python Lists</h2> <br>
* Lists are used to store multiple items in a single variable. <br>
* Lists are one of 4 built-in data types in Python used to store collections of data. <br>
* Lists are created using square brackets. <br>
* can change, add, and remove items in a list <br>

In [160]:
fruits = ["apple", "banana", "cherry"]
print(fruits)

['apple', 'banana', 'cherry']

In [83]:
#Lists allow duplicate values
apple = ["apple", "banana", "cherry", "apple", "cherry"]
print(apple)
len(apple)

['apple', 'banana', 'cherry', 'apple', 'cherry']

5

<b>To determine how many items a list has, use the <u>len()</u> function

In [167]:
fruits = ["apple", "banana", "cherry"]
print(len(fruits))

3

<b>List items can be of any data type

In [168]:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]

In [169]:
#A list can contain different data types
list1 = ["abc", 34, True, 40, "male"]

<b> We use the list() constructor when creating a new list.

In [171]:
fruits = list(("apple", "banana", "cherry")) # note the double round-brackets
print(fruits)

['apple', 'banana', 'cherry']

In [ ]:
# list((""))

<b>List items are indexed and you can access them by referring to the index number

In [90]:
fruits = ["apple", "banana", "cherry"]
print(fruits[:-1])

['apple', 'banana']

In [89]:
fruits = ["apple", "banana", "cherry"]
print(fruits[-1])

cherry

In [179]:
#slicing
fruits = ["apple", "banana", "cherry"]
print(fruits[:2])

['apple', 'banana']

In [183]:
fruits = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(fruits[-4:-1])

['orange', 'kiwi', 'melon']

<b>Check if Item Exists

In [91]:
fruit = ["apple", "banana", "cherry"]
if "apple" in fruit:
  print("Yes, 'apple' is in the fruits list")

Yes, 'apple' is in the fruits list

In [92]:
for i in fruit:
    if i=="apple":
        print("Yes, there is an apple")

Yes, there is an apple

<b>Change Item Value <br>
To change the value of a specific item, refer to the index number

In [95]:
fruit = ["apple", "banana", "cherry"]
fruit[-1] = "blackcurrant"
print(fruit)

['apple', 'banana', 'blackcurrant']

In [96]:
fruit = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
fruit[-1:-3] = ["blackcurrant", "watermelon"]
print(fruit)

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'blackcurrant', 'watermelon', 'mango']

In [188]:
fruit = ["apple", "banana", "cherry"]
fruit[1:3] = ["watermelon"]
print(fruit)

['apple', 'watermelon']

<b>Insert Items <br>
To insert a new list item, without replacing any of the existing values, we can use the <u>insert()</u> method.

In [190]:
fruit = ["apple", "banana", "cherry"]
fruit.insert(2, "watermelon")
print(fruit)

['apple', 'banana', 'watermelon', 'cherry']

<b>Append Items <br>
To add an item to the end of the list, use the <u>append()</u> method:

In [192]:
fruit = ["apple", "banana", "cherry"]
fruit.append("orange")
print(fruit)

['apple', 'banana', 'cherry', 'orange']

<b>Insert Items <br>
To insert a list item at a specified index, use the insert() method. <br>
<b>The insert() method inserts an item at the specified index

In [1]:
fruit = ["apple", "banana", "cherry"]
fruit.insert(1, "orange")
print(fruit)

['apple', 'orange', 'banana', 'cherry']

<b>Extend List <br>
To append elements from another list to the current list, use the <u>extend()</u> method.

In [2]:
thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)

['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']

In [3]:
a = [1, 7, 9, 0]
b = ["cat", "dog", "cow"]
c = ("bus", "car", "bike")

In [5]:
a.extend(b)
a

[1, 7, 9, 0, 'cat', 'dog', 'cow', 'cat', 'dog', 'cow']

<b>Add Any Iterable <br>
The <u>extend()</u> method does not have to append lists, you can add any iterable object (tuples, sets, dictionaries etc.).

In [12]:
thislist = ["apple", "banana", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

['apple', 'banana', 'cherry', 'kiwi', 'orange']

<b>Remove Specified Item <br>
The <u>remove()</u> method removes the specified item.

In [7]:
fruit = ["apple", "banana", "cherry"]
fruit.remove("banana")
print(fruit)

['apple', 'cherry']

In [8]:
fruit = ["apple", "banana", "cherry", "banana", "kiwi"]
fruit.remove("banana")
print(fruit)

['apple', 'cherry', 'banana', 'kiwi']

<b>Remove Specified Index <br>
The <u>pop()</u> method removes the specified index.

In [12]:
fruit = ["apple", "banana", "cherry"]
fruit.pop(0)
print(fruit)

['banana', 'cherry']

<b>If you do not specify the index, the pop() method removes the last item.

In [13]:
fruit = ["apple", "banana", "cherry"]
del fruit[0]
print(fruit)

['banana', 'cherry']

In [14]:
fruit = ["apple", "banana", "cherry"]
del fruit

In [15]:
fruit

NameError: name 'fruit' is not defined

<b>Clear the List <br>
The clear() method empties the list. <br>
<b>The list still remains, but it has no content. <br>

In [16]:
fruit = ["apple", "banana", "cherry"]
fruit.clear()
print(fruit)

[]

<b>Loop Through a List</b> <br>
You can loop through the list items by using a for loop

In [3]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry

<b>Loop Through the Index Numbers </b><br>
You can also loop through the list items by referring to their index number. <br>

Use the range() and len() functions to create a suitable iterable

In [18]:
fruits = ["apple", "banana", "cherry"]
len(fruits)
for i in range(len(fruits)):
    print(i)

0
1
2

In [19]:
fruits = ["apple", "banana", "cherry"]
for i in range(len(fruits)):
  print(fruits[i])

apple
banana
cherry

<b>Using a While Loop

In [20]:
fruits = ["apple", "banana", "cherry"]
i = 0
while i < len(fruits):
    # print(i)
    print(fruits[i])
    i = i + 1
#     i+=1

apple
banana
cherry

<b>Looping Using List Comprehension

In [25]:
fruits = ["apple", "banana", "cherry"]
a = [x for x in fruits]
a

['apple', 'banana', 'cherry']

In [24]:
fruits = ["apple", "banana", "cherry"]

for x in fruits:
    print(x)

apple
banana
cherry

<b>List Comprehension</b><br>
List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list.

In [3]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango,", 'deer']
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

['apple', 'banana', 'mango,']

In [30]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango", 'deer']

newlist = [x for x in fruits if "a" in x]

print(newlist)

['apple', 'banana', 'mango']

<b> Sort List Alphanumerically </b> <br>
List objects have a sort() method that will sort the list alphanumerically, ascending, by default

In [31]:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']

In [27]:
thislist = [100, 50, 65, 82, 23]
thislist.sort()
print(thislist[-1])

100

In [33]:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort(reverse = True)
print(thislist)

['pineapple', 'orange', 'mango', 'kiwi', 'banana']

In [28]:
thislist = [100, 50, 65, 82, 23]
thislist.sort(reverse = True)
print(thislist)

[100, 82, 65, 50, 23]

<h4>Task</h4>

<b>Program to Find Largest Number in a List

In [35]:
a = [10, 20, 4, 45, 99]

In [36]:
a.sort()

In [38]:
print("Largest element is:", a[-1])

Largest element is: 99

In [39]:
print("Largest element is:", max(a))

Largest element is: 99

In [15]:
x = 7 
input()

'hi'

In [32]:
# Python program to find largest
# number in a list
 
# Creating an empty list
list1 = []
 
# asking number of elements to put in list
num = int(input("Enter number of elements in list: "))
 
# Iterating till num to append elements in list
for i in range(num):
    ele = int(input("Enter elements: "))
    list1.append(ele)
 
# Printing maximum element
print("Largest element is:", max(list1))

Enter number of elements in list: 3
Enter elements: 43
Enter elements: 3
Enter elements: 67
Largest element is: 67

In [9]:
# # Python program to print odd Numbers in given range
 
# start, end = 4, 19
 
# # iterating each number in list
# for num in range(start, end+1):
     
#     # checking condition
#     if num % 2 != 0:
#         print(num, end = " ")

<b>Tuple</b><br>
* Tuples are used to store multiple items in a single variable. <br>
* It is ordered and unchangeable
* Tuples are written with round brackets.
*  It allows duplicate items

In [33]:
vechile = ("car", "bus", "bike", "car", 6)
print(vechile)

('car', 'bus', 'bike', 'car', 6)

In [34]:
print(type(vechile))

<class 'tuple'>

In [35]:
len(vechile)

5

In [38]:
vechile = ("car", ) # a single data in small bracket is not a tuple
                    # should be seperated by comma

In [39]:
type(vechile)

tuple

In [40]:
random = ("car", 34, 4.5, True) # tuple can be of different data type

In [36]:
random

('car', 34, 4.5, True)

In [41]:
# vechile = ("car", "bus", "bike", "car")
vechile = tuple(("car", "bus", "bike", "car"))

In [43]:
a  = list((1, 4, 6))
a

[1, 4, 6]

In [42]:
type(vechile)

tuple

In [44]:
vechile[-4:-2]

('car', 'bus')

In [45]:
if "car" in vechile:
    print("yes")

yes

<b>Once a tuple is created, you cannot change its values. Tuples are unchangeable, or <u>immutable</u> as it also is called.

In [46]:
vechile = ("car", "bus", "bike", "car")

In [47]:
x = list(vechile)

In [48]:
type(x)

list

In [50]:
x.append("daaaa")   #x.insert(1, 1)     #x[3] = 1

In [51]:
tuple(x)

('car', 'bus', 'bike', 'car', 'daaaa', 'daaaa')

In [73]:
#unpack tuple
vechile = ("car", "bus", "bike")
(x, y, z) = vechile
print(x)
print(y)
print(z)

car
bus
bike

In [72]:
# vechile = ("car", "bus", "bike", "1", "99")

In [52]:
# loop tuple using while loop
vechile = ("car", "bus", "bike", "1", "99")
i = 0
while i < len(vechile):
  print(vechile[i])
  i = i + 1

car
bus
bike
1
99

In [77]:
# To join two or more tuples you can use the + operator
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2
print(tuple3)

('a', 'b', 'c', 1, 2, 3)

<b>Python Sets</b><br>
* Sets are used to store multiple items in a single variable. (same as list and tuple)<br>
* A set is a collection which is unordered, unchangeable*, and unindexed.
* Sets are written with curly brackets.

In [53]:
vechile = {"car", "bus", "bike"}

In [54]:
print(type(vechile))

<class 'set'>

In [57]:
vechile = {"car", "bus", "bike", "bike"}  # no dupicate, duplicate value will be ignoredduplicate value will be ignored
print(vechile)

{'bike', 'bus', 'car'}

In [58]:
vechile

{'bike', 'bus', 'car'}

In [59]:
vechile = {"car", "bus", "bike", "bike", True, 1}  # no dupicate, duplicate value will be ignored
print(len(vechile))
print(vechile)

4
{'bike', True, 'bus', 'car'}

In [60]:
#It is also possible to use the set() constructor to make a set.
vechile = set(("car", "bus", "bike", "bike", True, 1))
print(vechile)

{'bike', 'bus', 'car', True}

In [63]:
#loop in set
for i  in vechile:
    print(i)

bike
bus
car
True

<b>add items in set using <u>add()</u>

In [64]:
#add items in set using add()
vechile = {"car", "bus", "bike"}
vechile.add("truck")
print(vechile)

{'bike', 'bus', 'truck', 'car'}

<b>To add items from another set into the current set, use the <u>update()</u> method.</b>

In [65]:
thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

thisset.update(tropical)

print(thisset)

{'banana', 'mango', 'pineapple', 'cherry', 'apple', 'papaya'}

In [66]:
thisset = {"apple", "banana", "cherry"}
mylist = ("kiwi", "orange")

thisset.update(mylist)

print(thisset)

{'banana', 'orange', 'cherry', 'kiwi', 'apple'}

<b>Remove a random item by using the <u>remove(), discard()</u> method

In [69]:
thisset = {"apple", "banana", "cherry"}

thisset.remove("banana")   #discard("banana")

# print(x)

print(thisset)

{'apple', 'cherry'}

<b>we can use <u>union()</u> and <u>update()</u> method to join sets

In [122]:
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)  #update(set2)
print(set3)

{'b', 1, 2, 3, 'c', 'a'}

<h2>Python Dictionaries</h2>
* Dictionaries are written with curly brackets, and have keys and values.<br>
* Dictionaries are used to store data values in key:value pairs. <br>
* A dictionary is a collection which is ordered*, changeable and do not allow duplicates. <br>

In [78]:
dict = {
  "brand": "Ford",     # values can be of any data types
  "model": "Mustang",
  "year": 1964
}
print(dict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [71]:
print(len(dict))

3

In [73]:
# Nested dictionary
students = {
  "student_1" : {
    "name" : "Anil",
    "year" : 2004
  },
  "student_2" : {
    "name" : "Sita",
    "year" : 2007
  },
  "student_3" : {
    "name" : "Laxmi",
    "year" : 2011
  }
}

In [75]:
students["student_1"]['name']

'Anil'

In [3]:
student_1 = {
    "name" : "Anil",
    "year" : 2004
  }

    
student_2 = {
    "name" : "Sita",
    "year" : 2007
  }

student_3 = {
    "name" : "Laxmi",
    "year" : 2011
  }

classSix = {
    "student_1": student_1, 
    "student_2": student_2, 
    "student_3": student_3
}

In [2]:
classSix['student_1']

{'name': 'Anil', 'year': 2004}

In [77]:
# access dictionary items
print(dict["brand"]) # with key

print(dict.get("brand")) # with get() method

Ford
Ford

<b>The <u>keys()</u> method will return a list of all the keys in the dictionary.

In [132]:
dict.keys()

dict_keys(['brand', 'model', 'year'])

<b>The <u>values()</u> method will return a list of all the values in the dictionary

In [79]:
dict.values()

dict_values(['Ford', 'Mustang', 1964])

In [80]:
# add or update dictionary keys
dict["year"]="2000"
dict

{'brand': 'Ford', 'model': 'Mustang', 'year': '2000'}

In [81]:
#Check if "model" is present in the dictionary
dict = {
  "brand": "Ford",    
  "model": "Mustang",
  "year": 1964
}

if "model" in dict:
    print("Yes")
else:
    print("no")

Yes

In [82]:
#using pop() method to remove dictionary items
dict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
dict.pop("model")
print(dict)

{'brand': 'Ford', 'year': 1964}

In [83]:
#loop in dictionary
for i in dict:
    print(i)

brand
year

In [154]:
for i in dict:
    print(dict[i])

Ford
1964

In [84]:
for i, j in dict.items():
    print(i, j)

brand Ford
year 1964

In [85]:

#copy dictionary with copy() method 
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
new_car = car.copy()
print(new_car)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [86]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.clear()

print(car)

{}

In [87]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.pop("model")

print(car)

{'brand': 'Ford', 'year': 1964}

<b>Python Collections (Arrays)</b> <br>
* List
* Tuple
* Set
* Dictionary

<b>Array</b><br>
An array is a special variable, which can hold more than one value at a time.

<h3>Python Functions</h3> <br>

* A function is a block of code which only runs when it is called.

* You can pass data, known as parameters, into a function.

* A function can return data as a result.

In [94]:
def my_function():
    print("Hello from a function")

my_function()

Hello from a function

In [2]:
def add(a, b):   # a and b are called parameter #A parameter is the variable listed inside the parentheses in the function definition. 
    z = a+b
#     print(z)
    return z
    
add(2, 4) # 2 & 4 are called argument # An argument is the value that is sent to the function when it is called.

6

<b>If you do not know how many arguments that will be passed into your function, add a * before the parameter name in the function definition.

In [100]:
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus

<b>Default Parameter Value</b><br>
If we call the function without argument, it uses the default value

In [101]:

def my_function(a=4, b=6):
  sum = a+b
  return sum

my_function()
# my_function(6, 6)

10

In [102]:
def my_function(food):
  for x in food:
    print(x)

fruits = {'c':"apple", 'd':"banana", 'e':"cherry"}

my_function(fruits)

c
d
e

<b>The pass Statement</b> <br>
function definitions cannot be empty, but if you for some reason have a function definition with no content, put in the <b><u>pass</u></b> statement to avoid getting an error.

In [6]:
def myfunction():
    pass

<h3>Exercise </h3>

Generate a Python list of all the even numbers between 4 to 30

In [106]:
list(range(4, 30, 2))

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

Find the largest item from a given list <br>
x = [4, 6, 8, 24, 12, 2]

In [20]:
x = [4, 6, 8, 24, 12, 2]
max(x)
# x.sort(reverse=True)
# z = x[0]
# print(z)

24

Define a function that accepts radius and returns the area of a circle. <br>
radius = 4 <br>
formula for area of circle = 2*π^2

In [113]:
def area(radius):
    area = 3.14*radius*radius
    return area

area(4)


# radius = float(input("Enter Radius: "))  # 4
# print(int(area(radius)))

Enter Radius: 4.1
52

In [ ]:
# program to find volume of a cube
v= l*b*h # formula

In [8]:
def volume_of_cube(l, b, h):
    v = l*b*h
    return v

volume_of_cube(3, 5, 2)

30

In [9]:
volume_of_cube(4, 6, 9)

216

In [12]:
# write a  function to detect if a person can vote with their age
age  = 13

if age > 18:
    print("The person ca n vote")
else:
    print("The person cannot vote")

The person cannot vote

In [13]:

def eligible_vote(age):
    if age > 18:
        print("The person ca n vote")
    else:
        print("The person cannot vote")
        
eligible_vote(28)

The person ca n vote

Write a Python function to sum all the numbers in a list. <br>
a = [2, 6, 9, 10] <br>
output: 27

In [114]:
# Define a function named 'sum' that takes a list of numbers as input
a = [2, 6, 9, 10]
# expeted output is : 27

def sum(numbers):
    # Initialize a variable 'total' to store the sum of numbers, starting at 0
    total = 0
    
    # Iterate through each element 'x' in the 'numbers' list
    for x in numbers:
        # Add the current element 'x' to the 'total'
        total += x
    
    # Return the final sum stored in the 'total' variable
    return total

# Print the result of calling the 'sum' function with a tuple of numbers (8, 2, 3, 0, 7)
print(sum(a))

27

Write a Python function to multiply all the numbers in a list. <br>
a = [2, 6, 9, 10] <br>
output: 1080

In [4]:
# Define a function named 'multiply' that takes a list of numbers as input
a = [2, 6, 9, 10] 

def multiply(numbers):
    # Initialize a variable 'total' to store the multiplication result, starting at 1
    total = 1
    
    # Iterate through each element 'x' in the 'numbers' list
    for x in numbers:
        # Multiply the current element 'x' with the 'total'
        total *= x
    
    # Return the final multiplication result stored in the 'total' variable
    return total

# Print the result of calling the 'multiply' function with a tuple of numbers (8, 2, 3, -1, 7)
print(multiply(a))

1080

<h3>Python Functions</h3> <br>

* A function is a block of code which only runs when it is called.

* You can pass data, known as parameters, into a function.

* A function can return data as a result.

In [197]:
def my_function():
  print("Hello from a function")

my_function()

Hello from a function

In [198]:
def add(a,b):   # a and b are called parameter #A parameter is the variable listed inside the parentheses in the function definition. 
    z = a+b
    # print(z)
    return z
    
add(2, 4) # 2 & 4 are called argument # An argument is the value that is sent to the function when it is called.

6

<b>If you do not know how many arguments that will be passed into your function, add a * before the parameter name in the function definition.

In [202]:
def my_function(*kids):
  print("The youngest child is " + kids[0])

my_function("Emil", "Tobias", "Linus")

The youngest child is Emil

<b>Default Parameter Value</b><br>
If we call the function without argument, it uses the default value

In [209]:

def my_function(a=4, b=6):
  sum = a+b
  return sum

my_function()
# my_function(6, 6)

10

In [213]:
def my_function(food):
  for x in food:
    print(x)

fruits = {'c':"apple", 'd':"banana", 'e':"cherry"}

my_function(fruits)

c
d
e

<b>The pass Statement</b> <br>
function definitions cannot be empty, but if you for some reason have a function definition with no content, put in the <b><u>pass</u></b> statement to avoid getting an error.

In [216]:
def myfunction():
  pass

# Python Class

# Simple Class

In [47]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def hello(self):
    print("Hello " + self.name)

p1 = Person("John", 36)
Person.hello(p1)
p1.hello()

Hello John
Hello John

In [49]:
class Student(Person):
    def __init__(self, name, age , school):
        super().__init__(name,age)
        self.school = school
    def welcome(self):
        self.hello()
        print("Welcome to our school of ",self.school)

s1 = Student("Bibek",29,"Code for Change")
s1.welcome()

Hello Bibek
Welcome to our school of  Code for Change

<h3>Exercise </h3>

Generate a Python list of all the even numbers between 4 to 30

Find the largest item from a given list <br>
x = [4, 6, 8, 24, 12, 2]

Define a function that accepts radius and returns the area of a circle. <br>
radius = 4 <br>
formula for area of circle = 2*π^2

Write a Python function to sum all the numbers in a list. <br>
a = [2, 6, 9, 10] <br>
output: 27

Write a Python function to multiply all the numbers in a list. <br>
a = [2, 6, 9, 10] <br>
output: 1080

<h4>Escape characters

<!DOCTYPE html>
<html>
<head>
    <title>Escape Characters Table</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Code</th>
            <th>Result</th>
        </tr>
        <tr>
            <td>\'</td>
            <td>Single Quote</td>
        </tr>
        <tr>
            <td>\\</td>
            <td>Backslash</td>
        </tr>
        <tr>
            <td>\n</td>
            <td>New line</td>
        </tr>
        <tr>
        <tr>
            <td>\t</td>
            <td>Tab</td>
        </tr>
        <tr>
            <td>\b</td>
            <td>Backspace</td>
        </tr>
    </table>
</body>
</html>

In [6]:
txt = 'They\'re playing.'
txt

"They're playing."

In [26]:
txt = "This will insert one\\ (backslash)."
print(txt)

This will insert one\ (backslash).

In [1]:
txt = "Hello this is my\n World!"
print(txt)

Hello this is my
 World!

<h4>Recursion</h4> <br>
* It means that a function calls itself.

In [12]:
# Syntax:
def func():
    func()

In [6]:
def addition(num):
    if num:
        # call same function by reducing number by 1
        return num + addition(num - 1)
    else:
        return 0

res = addition(10)
print(res)

55

In [34]:
#find factorial of a number using function
num = 0
def recursive_factorial(n):
  if n == 1:
      return n
  else:
      return n * recursive_factorial(n-1)
 
 
# check if the input is valid or not
if num < 0:
  print("Invalid input ! Please enter a positive number.")
elif num == 0:
  print("Factorial of number 0 is 1")
else:
  print("Factorial of number", num, "=", recursive_factorial(num))

Factorial of number 0 is 1

# Program to print the fibonacci series upto n_terms

<h2>Exception Handling</h2> <br>
When an error occurs, Python will normally stop and generate an error message. <br>

* Errors are the problems in a program due to which the program will stop the execution.<br>
* There are two types of Error occurs in python. <br>
      1. Syntax errors
      2. Logical errors (Exceptions)

In [38]:
a = 1
b = 0

c = 1/0 # as 1/0 is undefined 

print(c)

ZeroDivisionError: division by zero

<h3><b>Syntax errors </b></h3><br>
When the proper syntax of the language is not followed then a syntax error is thrown.

In [41]:
#program to show syntax error

# initialize the amount variable 
number = 't'
  
# check that You are eligible to 
#  purchase Dsa Self Paced or not 
if(number>2999):
    print("You are eligible to purchase Dsa Self Paced")

TypeError: '>' not supported between instances of 'str' and 'int'

<h3><b>logical errors(Exception) </b></h3><br>
When in the runtime an error that occurs after passing the syntax test is called exception or logical type.

In [9]:
# initialize the amount variable 
marks = 90
  
# perform division with 0 
a = marks / 0
print(a)

ZeroDivisionError: division by zero

In [42]:
a = [1, 5, 8, 9]
a[5]

IndexError: list index out of range

<!DOCTYPE html>
<html>
<head>
    <title>Two-Column Table</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Exception</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>IndexError</td>
            <td>When the wrong index of a list is retrieved.</td>
        </tr>
        <tr>
            <td>AssertionError</td>
            <td>It occurs when the assert statement fails</td>
        </tr>
        <tr>
            <td>AttributeError</td>
            <td>It occurs when an attribute assignment is failed.</td>
        </tr>
        <tr>
            <td>ImportError	</td>
            <td>It occurs when an imported module is not found.</td>
        </tr>
        <tr>
            <td>KeyError</td>
            <td>It occurs when the key of the dictionary is not found.</td>
        </tr>
        <tr>
            <td>NameError</td>
            <td>It occurs when the variable is not defined.</td>
        </tr>
        <tr>
            <td>MemoryError	</td>
            <td>It occurs when a program runs out of memory.</td>
        </tr>
        <tr>
            <td>TypeError</td>
            <td>It occurs when a function and operation are applied in an incorrect type.</td>
        </tr>
    </table>
</body>
</html>

<h2>Error Handling with Try Catch</h2> <br>

* Handling Exceptions with <b>Try/Except/Finally</b>
* The <b>try</b> block lets you test a block of code for errors.

* The <b>except</b> block lets you handle the error.

* The <b>else</b> block lets you execute code when there is no error.

* The <b>finally</b> block lets you execute code, regardless of the result of the try- and except blocks.

<b>Try and Except Statement</b>

In [43]:
marks = 90

a = marks/0
print(a)


# initialize the amount variable 
marks = 90
  
# perform division with 0 
try:
    a = marks / 0
    print(a) 
except:
    print("It is not divisible")

It is not divisible

<b>Try with Else Clause</b>

In [46]:
# Python code to illustrate working of try()  
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional
        # Part as Answer 
        result = x // y 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
    else:
        print("Yeah ! Your answer is :", result) 
   
# Look at parameters and note the working of Program 
divide(3, 2) 
# divide(3, 0)

Yeah ! Your answer is : 1

<b>Python finally Keyword</b>

In [54]:
# Python code to illustrate 
# working of try()  
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional 
        # Part as Answer 
        result = x // y 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
    else:
        print("Yeah ! Your answer is :", result) 
    finally:  
        # this block is always executed   
        # regardless of exception generation.  
        print('This is always executed')   
 
# Look at parameters and note the working of Program 
# divide(3, 2) 
divide(3, 0)

Sorry ! You are dividing by zero
This is always executed

<h2>Exception Handling</h2> <br>
When an error occurs, Python will normally stop and generate an error message. <br>

* Errors are the problems in a program due to which the program will stop the execution.<br>
* There are two types of Error occurs in python. <br>
      1. <b>Syntax errors <br>
      2. Logical errors (Exceptions)</b>

In [3]:
a = 1
b = 0

c = 1/0 # as 1/0 is undefined 

print(c)

ZeroDivisionError: division by zero

<h3><b>Syntax errors </b></h3><br>
When the proper syntax of the language is not followed then a syntax error is thrown.

In [7]:
#program to show syntax error

# initialize the amount variable 
number = 10000
  
# check that You are eligible to 
#  purchase Dsa Self Paced or not 
if(number>2999):
    print("You are eligible to purchase Dsa Self Paced")

SyntaxError: invalid syntax (549833291.py, line 8)

<h3><b>logical errors(Exception) </b></h3><br>
When in the runtime an error that occurs after passing the syntax test is called exception or logical type.

In [9]:
# initialize the amount variable 
marks = 90
  
# perform division with 0 
a = marks / 0
print(a)

ZeroDivisionError: division by zero

<!DOCTYPE html>
<html>
<head>
    <title>Two-Column Table</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Exception</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>IndexError</td>
            <td>When the wrong index of a list is retrieved.</td>
        </tr>
        <tr>
            <td>AssertionError</td>
            <td>It occurs when the assert statement fails</td>
        </tr>
        <tr>
            <td>AttributeError</td>
            <td>It occurs when an attribute assignment is failed.</td>
        </tr>
        <tr>
            <td>ImportError	</td>
            <td>It occurs when an imported module is not found.</td>
        </tr>
        <tr>
            <td>KeyError</td>
            <td>It occurs when the key of the dictionary is not found.</td>
        </tr>
        <tr>
            <td>NameError</td>
            <td>It occurs when the variable is not defined.</td>
        </tr>
        <tr>
            <td>MemoryError	</td>
            <td>It occurs when a program runs out of memory.</td>
        </tr>
        <tr>
            <td>TypeError</td>
            <td>It occurs when a function and operation are applied in an incorrect type.</td>
        </tr>
    </table>
</body>
</html>

<h2>Error Handling with Try Catch</h2> <br>

* Handling Exceptions with <b>Try/Except/Finally</b>
* The <b>try</b> block lets you test a block of code for errors.

* The <b>except</b> block lets you handle the error.

* The <b>else</b> block lets you execute code when there is no error.

* The <b>finally</b> block lets you execute code, regardless of the result of the try- and except blocks.

<b>Try and Except Statement</b>

In [10]:
# initialize the amount variable 
marks = 90
  
# perform division with 0 
try:
    a = marks / 0
    print(a) 
except:
    print("It is not divisible")

It is not divisible

<b>Try with Else Clause</b>

In [18]:
# Python code to illustrate working of try()  
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional
        # Part as Answer 
        result = x // y 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
    else:
        print("Yeah ! Your answer is :", result) 
   
# Look at parameters and note the working of Program 
divide(3, 2) 
# divide(3, 0)

Yeah ! Your answer is : 1

<b>Python finally Keyword</b>

In [20]:
# Python code to illustrate 
# working of try()  
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional 
        # Part as Answer 
        result = x // y 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
    else:
        print("Yeah ! Your answer is :", result) 
    finally:  
        # this block is always executed   
        # regardless of exception generation.  
        print('This is always executed')   
 
# Look at parameters and note the working of Program 
# divide(3, 2) 
divide(3, 0)

Sorry ! You are dividing by zero
This is always executed

<h3>Global and Local Variables in Python</h3>

<h3>Local variables</h3> <br>


* Defined inside the function <br>
* Local variables are accessible only inside the function

In [1]:
def f():
 
    # local variable
    s = "This is a data science class"
    print(s)
 
 
# calling function
f()

This is a data science class

In [4]:
def f():
 
    # local variable
    s = "This is a data science class"
    print(s)
 
 
# calling function
f()
# print(s)

#local variable cannot be used outside the function

This is a data science class

<h3>Global variables</h3> <br>

* Defined outside the function <br>
* global variables are accessible throughout the program

In [6]:
def check_marks(marks):
    if marks >= 42:
        print("pass")
    else:
        print("fail")

all_marks = 56  #global variable as it is outside the function

check_marks(all_marks)
print(all_marks)

pass
56

In [23]:
# This function uses global variable s
def f():
    print("Inside Function:", s)
 
# Global scope
s = "This is data science class"

f()

print("Outside Function:", s)

Inside Function: This is data science class
Outside Function: This is data science class

In [8]:
# This function has a variable with
# name same as s.
def f():
    s = "Me too."
    print(s)
 
# Global scope
s = "I love Geeksforgeeks"
f()
print(s)

Me too.
I love Geeksforgeeks

<b>To create a global variable inside a function, you can use the global keyword.

In [10]:
def myfunc():
    global x
    x = "fantastic"
    print(x)
myfunc()

print("Python is " + x)

fantastic
Python is fantastic

In [89]:
x = "awesome"

def myfunc():
  global x
  x = "fantastic"
  print(x)


myfunc()

# print("Python is " + x)

fantastic

<h2>File Handling in Python</h2>

* Python allows users to handle files i.e., to read and write files, update and delete files.
*  Python treats files as either text or binary

* The key function for working with files in Python is the <b>open()</b> function.<br>
* The <b>open()</b> function takes two parameters; <b>filename </b>, and <b>mode</b>.<br>
i.e. <b>open(filename, mode)</b>

There are four different methods (modes) for opening a file: <br>


<b>"r"</b> - Read - Default value. Opens a file for reading, error if the file does not exist

<b>"a"</b> - Append - Opens a file for appending, creates the file if it does not exist

<b>"w"</b> - Write - Opens a file for writing, creates the file if it does not exist

<b>"x"</b> - Create - Creates the specified file, returns an error if the file exists

You can specify if the file should be handled as binary or text mode <br>

<b>"t"</b> - Text - Default value. Text mode

<b>"b"</b>- Binary - Binary mode (e.g. images)

In [29]:
# f = open("demofile.txt", "rt")

<h4>Working in Read mode</h4>

In [18]:
f = open('data/file.txt', "r")
print(f.read())
f.close()

Hello,
Fellow CFCs.
How are you all?

In [19]:
with open('data/file.txt', 'r') as f:
    print(f.read()) #using with automatically closes the file

Hello,
Fellow CFCs.
How are you all?

In [20]:
f = open("data/file.txt", "r")
print(f.read())

Hello,
Fellow CFCs.
How are you all?

In [22]:
f = open("data/file.txt", "r") #you can also specify how many characters you want to return
print(f.read(11))

Hello,
Fell

<b>Read Lines</b> <br>
You can return one line by using the <b>readline()</b> method.

In [23]:
f = open("data/file.txt", "r")
print(f.readline())
print(f.readline())

Hello,

Fellow CFCs.

In [25]:
f = open("data/file.txt", "r")
for x in f:
    print(x)
  # print(x.split())

Hello,

Fellow CFCs.

How are you all?

In [26]:
f = open("data/file.txt", "r")
print(f.readline())
f.close() #closes the file # The close() command terminates all the resources in use

Hello,

<h4>Working in Write Mode</h4>
using write() method

In [28]:
# Python code to create a file
file = open('data/new_file.txt','w')
file.write("This is a test file\n This is a test file\n ") 
file.close()

using append() method

In [31]:
# Python code to illustrate append() mode
file = open('data/new_file.txt', 'a')
file.write("This will add this line \n")
file.close()

In [30]:
# with open('test.txt', 'a') as file:
#     file.write("This will add this line")

<h4>Delete a File</h4>
To delete a file, you must import the OS module, and run its <b>os.remove()</b> function

In [32]:
import os
os.remove("data/new_file.txt")

In [33]:
#check if file exists
import os

if os.path.exists("new_file.txt"):
  os.remove("file.txt")
else:
  print("The file does not exist")

The file does not exist

<h4>Delete Folder</h4>
To delete an entire folder, use the <b>os.rmdir()</b> method.

In [81]:
import os
os.rmdir("name")

<h3> Python RegEx </h3> <br> 

* A RegEx, or Regular Expression, is a sequence of characters that forms a search pattern.
* Python has a built-in package called re, which can be used to work with Regular Expressions.

<h4> RegEx Module</h4> 
Python has a built-in package called <b>re</b>, which can be used to work with Regular Expressions.

In [42]:
import re

In [68]:
import re

#Check if the string starts with "The" and ends with "Spain":

txt = "I am a data science student dog"

x = re.search("^I.*dog$", txt)

if x:
  print("YES! We have a match!")
else:
  print("No match")

YES! We have a match!

In [66]:
# A Python program to demonstrate working of  
# findall()  
import re  
    
# A sample text string where regular expression   
# is searched.  
string = """Hello my Number is 123456789 and  
             my friend's number is 987654321"""
    
# A sample regular expression to find digits.  
regex = '\d+'             
    
match = re.findall(regex, string)  
print(match)

['123456789', '987654321']

In [51]:
import re

text = "Sample text with a Nepali phone number: +977 9849240444. Another number: +977 9812345678."

nepali_phone_numbers = re.findall(r'\+977\s?\d{10}', text)
print(nepali_phone_numbers)

['+977 9849240444', '+977 9812345678']

<h4>Why RegEx? </h4> <br>

* Data Mining (best tool for data mining) <br>
      - phone no, url, email etc.<br>
  
* Data Validation (perfectly validate data)<br>
      - validating phone numbers, emails<br>

<!DOCTYPE html>
<html>
<head>
  <title>Metacharacters</title>
</head>
<body>

<table border="1">
  <tr>
    <th>Character</th>
    <th>Description</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>[]</td>
    <td>A set of characters</td>
    <td>"[a-m]"</td>
  </tr>
  <tr>
    <td>\</td>
    <td>Signals a special sequence</td>
    <td>"\d"</td>
  </tr>
    <td>^</td>
    <td>Starts with</td>
    <td>"^hello"</td>
  <tr>

  </tr>
    <td>.</td>
    <td>Any character</td>
    <td>"he..o"	</td>
  <tr>


  </tr>
    <td>*</td>
    <td>Zero or more occurrences</td>
    <td>"he.*o"</td>
  <tr>

  </tr>
    <td>+</td>
    <td>One or more occurrences</td>
    <td>"he.+o"</td>
  <tr>

  </tr>
    <td>?</td>
    <td>Zero or more occurrences</td>
    <td>"he?*o"</td>
  <tr>

  </tr>
    <td>{}</td>
    <td>Exactly the specified number of occurrences	</td>
    <td>"he.{2}o"</td>
  <tr>

  </tr>
    <td>|</td>
    <td>Either or</td>
    <td>"falls|stays"</td>
  <tr>

  </tr>
    <td> dollar sign</td>
    <td>Ends with	</td>
    <td>  "planet$"  </td>
  <tr>
      
  </tr>
</table>

</body>
</html>

In [70]:
import re

txt = "The cost of a pen is Rs 10 and pencil is Rs 5."

#Find all lower case characters alphabetically between "a" and "m":

x = re.findall("[0-9]", txt)  # 0-90
print(x)

['1', '0', '5']

In [71]:
import re

txt = "The cost of a pen is Rs 10 and pencil is Rs 5."

#Find all digit characters:

x = re.findall("\d", txt)
print(x)

['1', '0', '5']

In [72]:
import re

txt = "hello python"

#Search for a sequence that starts with "he", followed by two (any) characters, and an "o":

x = re.findall("he..o", txt)
print(x)

['hello']

In [66]:
import re

txt = "hello python"

#Check if the string starts with 'hello':

x = re.findall("^hello", txt)
if x:
  print("Yes, the string starts with 'hello'")
else:
  print("No match")

Yes, the string starts with 'hello'

In [69]:
import re

txt = "hello python"

#Check if the string ends with 'planet':

x = re.findall("python$", txt)
if x:
  print("Yes, the string ends with 'planet'")
else:
  print("No match")

Yes, the string ends with 'planet'

<h4> RegEx Functions</h4>

<!DOCTYPE html>
<html>
<head>
  <title>Table Example</title>
</head>
<body>

<table border="1">
  <tr>
    <th>Function</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>findall</td>
    <td>Returns a list containing all matches</td>
  </tr>
  <tr>
    <td>search</td>
    <td>Returns a Match object if there is a match anywhere in the string</td>
  </tr>
  <tr>
    <td>split</td>
    <td>Returns a list where the string has been split at each match</td>
  </tr>
  <tr>
    <td>sub</td>
    <td>Replaces one or many matches with a string</td>
  </tr>
</table>

</body>
</html>

<h4> The findall() Function </h4><br>
The <b>findall()</b> function returns a list containing all matches

In [74]:
import re

txt = "The rain in portugal, spain"

#Check if "Portugal" is in the string:

x = re.findall("portugal", txt)
print(x)

if (x):
  print("Yes, there is at least one match!")
else:
  print("No match")

['portugal']
Yes, there is at least one match!

In [80]:
import re

text = "Thee catt"
matches = re.findall(r'\b\w{4}\b', text)  # Matches three-letter words
print(matches)  # Output: ['cat', 'and', 'the', 'hat', 'sat', 'the', 'mat']

['Thee', 'catt']

If no matches are found, an empty list is returned

<h4>The <b>search()</b> Function</h4> <br>
The search() function searches the string for a match, and returns a Match object if there is a match.

In [94]:
import re

txt = "The rain in Spain"
x = re.search("Spain", txt)
print(x)

<re.Match object; span=(12, 17), match='Spain'>

In [79]:
import re

text = "The cat and the hat sat on the mat."

match = re.search(r'\b\w{3}\b', text)  # Searches for the first three-letter word

if match:
    print(match.group())  # Output: 'cat'

The

This method stops after the first match

<h4>The <b>split()</b> Function </h4> <br>
The split() function returns a list where the string has been split at each match

In [85]:
import re

#Split the string at every white-space character:

txt = "The rain,  in Spain"
x = re.split(",", txt)
print(x)

['The rain', '  in Spain']

<h4> The <b>sub()</b> Function </h4> <br>
The sub() function replaces the matches with the text of your choice

In [86]:
import re

txt = "The rain in Spain"
x = re.sub("rain", "  ", txt)
print(x)

The    in Spain